// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("get_dst_buf"));
    static final VarHandle const$1 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("run"));
    static final VarHandle const$2 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("destroy"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("xsize"),
        JAVA_INT.withName("ysize")
    ).withName("");
    static final VarHandle const$4 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("xsize"));
    static final VarHandle const$5 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("ysize"));
}


