// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetColorAsEncodedProfile",
        constants$25.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetICCProfileSize",
        constants$25.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetColorAsICCProfile",
        constants$25.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetPreferredColorProfile",
        constants$24.const$1
    );
}


