// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderSizeHintBasicInfo",
        constants$22.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderSubscribeEvents",
        constants$22.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetKeepOrientation",
        constants$22.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetUnpremultiplyAlpha",
        constants$22.const$2
    );
}


