// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("duration"),
        JAVA_INT.withName("timecode"),
        JAVA_INT.withName("name_length"),
        JAVA_INT.withName("is_last"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("have_crop"),
            JAVA_INT.withName("crop_x0"),
            JAVA_INT.withName("crop_y0"),
            JAVA_INT.withName("xsize"),
            JAVA_INT.withName("ysize"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("blendmode"),
                JAVA_INT.withName("source"),
                JAVA_INT.withName("alpha"),
                JAVA_INT.withName("clamp")
            ).withName("blend_info"),
            JAVA_INT.withName("save_as_reference")
        ).withName("layer_info")
    ).withName("");
    static final VarHandle const$1 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("duration"));
    static final VarHandle const$2 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("timecode"));
    static final VarHandle const$3 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("name_length"));
    static final VarHandle const$4 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("is_last"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jpegxl_alloc_func.class, "apply", constants$4.const$3);
}


