// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("have_crop"));
    static final VarHandle const$1 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_x0"));
    static final VarHandle const$2 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_y0"));
    static final VarHandle const$3 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("xsize"));
    static final VarHandle const$4 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("ysize"));
    static final VarHandle const$5 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("save_as_reference"));
}


