// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetRenderSpotcolors",
        constants$22.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetCoalescing",
        constants$22.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderProcessInput",
        constants$21.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetInput",
        constants$23.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseInput",
        constants$22.const$0
    );
}


