// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("rendering_intent"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("num_channels"),
        JAVA_INT.withName("data_type"),
        JAVA_INT.withName("endianness"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("align")
    ).withName("");
    static final VarHandle const$2 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("num_channels"));
    static final VarHandle const$3 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("data_type"));
    static final VarHandle const$4 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("endianness"));
    static final VarHandle const$5 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("align"));
}


