// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("tps_numerator"),
        JAVA_INT.withName("tps_denominator"),
        JAVA_INT.withName("num_loops"),
        JAVA_INT.withName("have_timecodes")
    ).withName("");
    static final VarHandle const$1 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("tps_numerator"));
    static final VarHandle const$2 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("tps_denominator"));
    static final VarHandle const$3 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("num_loops"));
    static final VarHandle const$4 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("have_timecodes"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("have_container"),
        JAVA_INT.withName("xsize"),
        JAVA_INT.withName("ysize"),
        JAVA_INT.withName("bits_per_sample"),
        JAVA_INT.withName("exponent_bits_per_sample"),
        JAVA_FLOAT.withName("intensity_target"),
        JAVA_FLOAT.withName("min_nits"),
        JAVA_INT.withName("relative_to_max_display"),
        JAVA_FLOAT.withName("linear_below"),
        JAVA_INT.withName("uses_original_profile"),
        JAVA_INT.withName("have_preview"),
        JAVA_INT.withName("have_animation"),
        JAVA_INT.withName("orientation"),
        JAVA_INT.withName("num_color_channels"),
        JAVA_INT.withName("num_extra_channels"),
        JAVA_INT.withName("alpha_bits"),
        JAVA_INT.withName("alpha_exponent_bits"),
        JAVA_INT.withName("alpha_premultiplied"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("xsize"),
            JAVA_INT.withName("ysize")
        ).withName("preview"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("tps_numerator"),
            JAVA_INT.withName("tps_denominator"),
            JAVA_INT.withName("num_loops"),
            JAVA_INT.withName("have_timecodes")
        ).withName("animation"),
        JAVA_INT.withName("intrinsic_xsize"),
        JAVA_INT.withName("intrinsic_ysize"),
        MemoryLayout.sequenceLayout(100, JAVA_BYTE).withName("padding")
    ).withName("");
}


