// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("orientation"));
    static final VarHandle const$1 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("num_color_channels"));
    static final VarHandle const$2 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("num_extra_channels"));
    static final VarHandle const$3 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("alpha_bits"));
    static final VarHandle const$4 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("alpha_exponent_bits"));
    static final VarHandle const$5 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("alpha_premultiplied"));
}


