// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelInfo",
        constants$24.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelName",
        constants$24.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderFrameSettingsSetOption",
        constants$45.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderFrameSettingsSetFloatOption",
        constants$45.const$4
    );
}


