// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("intrinsic_xsize"));
    static final VarHandle const$1 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("intrinsic_ysize"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("bits_per_sample"),
        JAVA_INT.withName("exponent_bits_per_sample"),
        JAVA_INT.withName("dim_shift"),
        JAVA_INT.withName("name_length"),
        JAVA_INT.withName("alpha_premultiplied"),
        MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("spot_color"),
        JAVA_INT.withName("cfa_channel")
    ).withName("");
    static final VarHandle const$3 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$4 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("bits_per_sample"));
    static final VarHandle const$5 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("exponent_bits_per_sample"));
}


