// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("set_fields_data"),
        RuntimeHelper.POINTER.withName("set_fields_from_icc"),
        RuntimeHelper.POINTER.withName("init_data"),
        RuntimeHelper.POINTER.withName("init"),
        RuntimeHelper.POINTER.withName("get_src_buf"),
        RuntimeHelper.POINTER.withName("get_dst_buf"),
        RuntimeHelper.POINTER.withName("run"),
        RuntimeHelper.POINTER.withName("destroy")
    ).withName("");
    static final VarHandle const$1 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("set_fields_data"));
    static final VarHandle const$2 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("set_fields_from_icc"));
    static final VarHandle const$3 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("init_data"));
    static final VarHandle const$4 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("init"));
    static final VarHandle const$5 = constants$6.const$0.varHandle(MemoryLayout.PathElement.groupElement("get_src_buf"));
}


