// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JxlChunkedFrameInputSource.get_color_channel_data_at.class, "apply", constants$39.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$39.const$5
    );
    static final VarHandle const$2 = constants$39.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_color_channel_data_at"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JxlChunkedFrameInputSource.get_extra_channel_pixel_format.class, "apply", constants$40.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$40.const$3
    );
}


