// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$44 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$44() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderInitFrameHeader",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderInitBlendInfo",
        constants$5.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetBasicInfo",
        constants$24.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetUpsamplingMode",
        constants$44.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "JxlEncoderInitExtraChannelInfo",
        constants$44.const$5
    );
}


