// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$33 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$33() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsCreate",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsDestroy",
        constants$5.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsGet",
        constants$33.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsMerge",
        constants$17.const$0
    );
}


