// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseBoxes",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseFrames",
        constants$5.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseInput",
        constants$5.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetColorEncoding",
        constants$24.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetICCProfile",
        constants$23.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderInitBasicInfo",
        constants$5.const$3
    );
}


