// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlResizableParallelRunnerDestroy",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunner",
        constants$19.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunnerCreate",
        constants$4.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunnerDestroy",
        constants$5.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunnerDefaultNumWorkerThreads",
        constants$50.const$4
    );
}


