// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$38 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$38() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JxlEncoderOutputProcessor.seek.class, "apply", constants$21.const$0);
    static final VarHandle const$1 = constants$36.const$3.varHandle(MemoryLayout.PathElement.groupElement("seek"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JxlEncoderOutputProcessor.set_finalized_position.class, "apply", constants$21.const$0);
    static final VarHandle const$3 = constants$36.const$3.varHandle(MemoryLayout.PathElement.groupElement("set_finalized_position"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("opaque"),
            RuntimeHelper.POINTER.withName("get_buffer"),
            RuntimeHelper.POINTER.withName("release_buffer"),
            RuntimeHelper.POINTER.withName("seek"),
            RuntimeHelper.POINTER.withName("set_finalized_position")
        ).withName("JxlEncoderOutputProcessor")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetOutputProcessor",
        constants$38.const$4
    );
}


