// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$2.const$4
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_LONG.withName("size")
        ).withName("icc"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("color_space"),
            JAVA_INT.withName("white_point"),
            MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("white_point_xy"),
            JAVA_INT.withName("primaries"),
            MemoryLayout.paddingLayout(4),
            MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_red_xy"),
            MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_green_xy"),
            MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_blue_xy"),
            JAVA_INT.withName("transfer_function"),
            MemoryLayout.paddingLayout(4),
            JAVA_DOUBLE.withName("gamma"),
            JAVA_INT.withName("rendering_intent"),
            MemoryLayout.paddingLayout(4)
        ).withName("color_encoding"),
        JAVA_LONG.withName("num_channels")
    ).withName("");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("data"),
        JAVA_LONG.withName("size")
    ).withName("");
    static final VarHandle const$3 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final VarHandle const$4 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final VarHandle const$5 = constants$3.const$1.varHandle(MemoryLayout.PathElement.groupElement("num_channels"));
}


