// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetBoxSizeRaw",
        constants$24.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetBoxSizeContents",
        constants$24.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetProgressiveDetail",
        constants$22.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetIntendedDownsamplingRatio",
        constants$22.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderFlushImage",
        constants$21.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetImageOutBitDepth",
        constants$24.const$1
    );
}


