// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlColorEncodingSetToLinearSRGB",
        constants$47.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderAllowExpertOptions",
        constants$5.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JxlDebugImageCallback.class, "apply", constants$48.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$48.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetDebugImageCallback",
        constants$48.const$5
    );
}


