// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final VarHandle const$0 = constants$39.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_extra_channel_pixel_format"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JxlChunkedFrameInputSource.get_extra_channel_data_at.class, "apply", constants$41.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$41.const$1
    );
    static final VarHandle const$4 = constants$39.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_extra_channel_data_at"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JxlChunkedFrameInputSource.release_buffer.class, "apply", constants$17.const$0);
}


