// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlSignatureCheck",
        constants$18.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderCreate",
        constants$20.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderReset",
        constants$5.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderDestroy",
        constants$5.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderRewind",
        constants$5.const$3
    );
}


