// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameBitDepth",
        constants$24.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderAddJPEGFrame",
        constants$23.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderAddImageFrame",
        constants$26.const$2
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque"),
        RuntimeHelper.POINTER.withName("get_buffer"),
        RuntimeHelper.POINTER.withName("release_buffer"),
        RuntimeHelper.POINTER.withName("seek"),
        RuntimeHelper.POINTER.withName("set_finalized_position")
    ).withName("JxlEncoderOutputProcessor");
    static final VarHandle const$4 = constants$36.const$3.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


