// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderVersion",
        constants$19.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderCreate",
        constants$20.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderReset",
        constants$5.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderDestroy",
        constants$5.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("set_fields_data"),
            RuntimeHelper.POINTER.withName("set_fields_from_icc"),
            RuntimeHelper.POINTER.withName("init_data"),
            RuntimeHelper.POINTER.withName("init"),
            RuntimeHelper.POINTER.withName("get_src_buf"),
            RuntimeHelper.POINTER.withName("get_dst_buf"),
            RuntimeHelper.POINTER.withName("run"),
            RuntimeHelper.POINTER.withName("destroy")
        ).withName("")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetCms",
        constants$34.const$4
    );
}


