// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("blendmode"),
        JAVA_INT.withName("source"),
        JAVA_INT.withName("alpha"),
        JAVA_INT.withName("clamp")
    ).withName("");
    static final VarHandle const$1 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("blendmode"));
    static final VarHandle const$2 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("source"));
    static final VarHandle const$3 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("alpha"));
    static final VarHandle const$4 = constants$14.const$0.varHandle(MemoryLayout.PathElement.groupElement("clamp"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("have_crop"),
        JAVA_INT.withName("crop_x0"),
        JAVA_INT.withName("crop_y0"),
        JAVA_INT.withName("xsize"),
        JAVA_INT.withName("ysize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("blendmode"),
            JAVA_INT.withName("source"),
            JAVA_INT.withName("alpha"),
            JAVA_INT.withName("clamp")
        ).withName("blend_info"),
        JAVA_INT.withName("save_as_reference")
    ).withName("");
}


