// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderFlushInput",
        constants$21.const$2
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque"),
        RuntimeHelper.POINTER.withName("get_color_channels_pixel_format"),
        RuntimeHelper.POINTER.withName("get_color_channel_data_at"),
        RuntimeHelper.POINTER.withName("get_extra_channel_pixel_format"),
        RuntimeHelper.POINTER.withName("get_extra_channel_data_at"),
        RuntimeHelper.POINTER.withName("release_buffer")
    ).withName("JxlChunkedFrameInputSource");
    static final VarHandle const$2 = constants$39.const$1.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JxlChunkedFrameInputSource.get_color_channels_pixel_format.class, "apply", constants$17.const$0);
    static final VarHandle const$4 = constants$39.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_color_channels_pixel_format"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
}


