// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetDesiredIntensityTarget",
        constants$26.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetOutputColorProfile",
        constants$26.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("set_fields_data"),
            RuntimeHelper.POINTER.withName("set_fields_from_icc"),
            RuntimeHelper.POINTER.withName("init_data"),
            RuntimeHelper.POINTER.withName("init"),
            RuntimeHelper.POINTER.withName("get_src_buf"),
            RuntimeHelper.POINTER.withName("get_dst_buf"),
            RuntimeHelper.POINTER.withName("run"),
            RuntimeHelper.POINTER.withName("destroy")
        ).withName("")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetCms",
        constants$26.const$4
    );
}


