// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(jpegxl_free_func.class, "apply", constants$17.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$17.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("opaque"),
        RuntimeHelper.POINTER.withName("alloc"),
        RuntimeHelper.POINTER.withName("free")
    ).withName("JxlMemoryManagerStruct");
    static final VarHandle const$4 = constants$17.const$3.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final VarHandle const$5 = constants$17.const$3.varHandle(MemoryLayout.PathElement.groupElement("alloc"));
}


