// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("dim_shift"));
    static final VarHandle const$1 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("name_length"));
    static final VarHandle const$2 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("alpha_premultiplied"));
    static final VarHandle const$3 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("cfa_channel"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("extensions")
    ).withName("");
    static final VarHandle const$5 = constants$13.const$4.varHandle(MemoryLayout.PathElement.groupElement("extensions"));
}


