// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetParallelRunner",
        constants$21.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderGetError",
        constants$21.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderProcessOutput",
        constants$21.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameHeader",
        constants$24.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelBlendInfo",
        constants$24.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameName",
        constants$24.const$1
    );
}


