// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlDecoderPreviewOutBufferSize",
        constants$21.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetPreviewOutBuffer",
        constants$26.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetFrameHeader",
        constants$24.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetFrameName",
        constants$23.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetExtraChannelBlendInfo",
        constants$24.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderImageOutBufferSize",
        constants$21.const$4
    );
}


