// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JxlEncoderOutputProcessor.get_buffer.class, "apply", constants$36.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$36.const$5
    );
    static final VarHandle const$2 = constants$36.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_buffer"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JxlEncoderOutputProcessor.release_buffer.class, "apply", constants$21.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$21.const$0
    );
    static final VarHandle const$5 = constants$36.const$3.varHandle(MemoryLayout.PathElement.groupElement("release_buffer"));
}


