// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("color_space"),
        JAVA_INT.withName("white_point"),
        MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("white_point_xy"),
        JAVA_INT.withName("primaries"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_red_xy"),
        MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_green_xy"),
        MemoryLayout.sequenceLayout(2, JAVA_DOUBLE).withName("primaries_blue_xy"),
        JAVA_INT.withName("transfer_function"),
        MemoryLayout.paddingLayout(4),
        JAVA_DOUBLE.withName("gamma"),
        JAVA_INT.withName("rendering_intent"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("color_space"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("white_point"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("primaries"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("transfer_function"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("gamma"));
}


