// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlEncoderUseContainer",
        constants$22.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderStoreJPEGMetadata",
        constants$22.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetCodestreamLevel",
        constants$22.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderGetRequiredCodestreamLevel",
        constants$21.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameLossless",
        constants$22.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameDistance",
        constants$26.const$0
    );
}


