// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelDistance",
        constants$47.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlEncoderDistanceFromQuality",
        constants$47.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlEncoderFrameSettingsCreate",
        constants$36.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "JxlColorEncodingSetToSRGB",
        constants$47.const$5
    );
}


