// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetJPEGBuffer",
        constants$23.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseJPEGBuffer",
        constants$22.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetBoxBuffer",
        constants$23.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseBoxBuffer",
        constants$22.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetDecompressBoxes",
        constants$22.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "JxlDecoderGetBoxType",
        constants$31.const$5
    );
}


