// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("min_nits"));
    static final VarHandle const$1 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("relative_to_max_display"));
    static final VarHandle const$2 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("linear_below"));
    static final VarHandle const$3 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("uses_original_profile"));
    static final VarHandle const$4 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("have_preview"));
    static final VarHandle const$5 = constants$8.const$5.varHandle(MemoryLayout.PathElement.groupElement("have_animation"));
}


