// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$18.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JxlParallelRunner.class, "apply", constants$19.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$19.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderVersion",
        constants$19.const$4
    );
}


