// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*jpegxl_cms_set_fields_from_icc_func)(void* user_data,unsigned char* icc_data,unsigned long long icc_size,struct * c,int* cmyk);
 * }
 */
public interface jpegxl_cms_set_fields_from_icc_func {

    int apply(java.lang.foreign.MemorySegment user_data, java.lang.foreign.MemorySegment icc_data, long icc_size, java.lang.foreign.MemorySegment c, java.lang.foreign.MemorySegment cmyk);
    static MemorySegment allocate(jpegxl_cms_set_fields_from_icc_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2.const$5, fi, constants$2.const$4, scope);
    }
    static jpegxl_cms_set_fields_from_icc_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _user_data, java.lang.foreign.MemorySegment _icc_data, long _icc_size, java.lang.foreign.MemorySegment _c, java.lang.foreign.MemorySegment _cmyk) -> {
            try {
                return (int)constants$3.const$0.invokeExact(symbol, _user_data, _icc_data, _icc_size, _c, _cmyk);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


