// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*jpegxl_free_func)(void* opaque,void* address);
 * }
 */
public interface jpegxl_free_func {

    void apply(java.lang.foreign.MemorySegment opaque, java.lang.foreign.MemorySegment address);
    static MemorySegment allocate(jpegxl_free_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$17.const$1, fi, constants$17.const$0, scope);
    }
    static jpegxl_free_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _opaque, java.lang.foreign.MemorySegment _address) -> {
            try {
                constants$17.const$2.invokeExact(symbol, _opaque, _address);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


