// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*jpegxl_cms_destroy_func)(void*);
 * }
 */
public interface jpegxl_cms_destroy_func {

    void apply(java.lang.foreign.MemorySegment run_opaque);
    static MemorySegment allocate(jpegxl_cms_destroy_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$5.const$4, fi, constants$5.const$3, scope);
    }
    static jpegxl_cms_destroy_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _run_opaque) -> {
            try {
                constants$5.const$5.invokeExact(symbol, _run_opaque);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


