// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void* (*jpegxl_alloc_func)(void* opaque,unsigned long long size);
 * }
 */
public interface jpegxl_alloc_func {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment opaque, long size);
    static MemorySegment allocate(jpegxl_alloc_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$16.const$5, fi, constants$4.const$3, scope);
    }
    static jpegxl_alloc_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _opaque, long _size) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$4.const$5.invokeExact(symbol, _opaque, _size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


