// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     JxlBlendMode blendmode;
 *     uint32_t source;
 *     uint32_t alpha;
 *     int clamp;
 * };
 * }
 */
public class JxlBlendInfo {

    public static MemoryLayout $LAYOUT() {
        return constants$14.const$0;
    }
    public static VarHandle blendmode$VH() {
        return constants$14.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * JxlBlendMode blendmode;
     * }
     */
    public static int blendmode$get(MemorySegment seg) {
        return (int)constants$14.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * JxlBlendMode blendmode;
     * }
     */
    public static void blendmode$set(MemorySegment seg, int x) {
        constants$14.const$1.set(seg, x);
    }
    public static int blendmode$get(MemorySegment seg, long index) {
        return (int)constants$14.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void blendmode$set(MemorySegment seg, long index, int x) {
        constants$14.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle source$VH() {
        return constants$14.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t source;
     * }
     */
    public static int source$get(MemorySegment seg) {
        return (int)constants$14.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t source;
     * }
     */
    public static void source$set(MemorySegment seg, int x) {
        constants$14.const$2.set(seg, x);
    }
    public static int source$get(MemorySegment seg, long index) {
        return (int)constants$14.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void source$set(MemorySegment seg, long index, int x) {
        constants$14.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle alpha$VH() {
        return constants$14.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t alpha;
     * }
     */
    public static int alpha$get(MemorySegment seg) {
        return (int)constants$14.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t alpha;
     * }
     */
    public static void alpha$set(MemorySegment seg, int x) {
        constants$14.const$3.set(seg, x);
    }
    public static int alpha$get(MemorySegment seg, long index) {
        return (int)constants$14.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void alpha$set(MemorySegment seg, long index, int x) {
        constants$14.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle clamp$VH() {
        return constants$14.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int clamp;
     * }
     */
    public static int clamp$get(MemorySegment seg) {
        return (int)constants$14.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int clamp;
     * }
     */
    public static void clamp$set(MemorySegment seg, int x) {
        constants$14.const$4.set(seg, x);
    }
    public static int clamp$get(MemorySegment seg, long index) {
        return (int)constants$14.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void clamp$set(MemorySegment seg, long index, int x) {
        constants$14.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


