// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     JxlBitDepthType type;
 *     uint32_t bits_per_sample;
 *     uint32_t exponent_bits_per_sample;
 * };
 * }
 */
public class JxlBitDepth {

    public static MemoryLayout $LAYOUT() {
        return constants$2.const$0;
    }
    public static VarHandle type$VH() {
        return constants$2.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * JxlBitDepthType type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$2.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * JxlBitDepthType type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$2.const$1.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$2.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$2.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle bits_per_sample$VH() {
        return constants$2.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t bits_per_sample;
     * }
     */
    public static int bits_per_sample$get(MemorySegment seg) {
        return (int)constants$2.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t bits_per_sample;
     * }
     */
    public static void bits_per_sample$set(MemorySegment seg, int x) {
        constants$2.const$2.set(seg, x);
    }
    public static int bits_per_sample$get(MemorySegment seg, long index) {
        return (int)constants$2.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void bits_per_sample$set(MemorySegment seg, long index, int x) {
        constants$2.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle exponent_bits_per_sample$VH() {
        return constants$2.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t exponent_bits_per_sample;
     * }
     */
    public static int exponent_bits_per_sample$get(MemorySegment seg) {
        return (int)constants$2.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t exponent_bits_per_sample;
     * }
     */
    public static void exponent_bits_per_sample$set(MemorySegment seg, int x) {
        constants$2.const$3.set(seg, x);
    }
    public static int exponent_bits_per_sample$get(MemorySegment seg, long index) {
        return (int)constants$2.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void exponent_bits_per_sample$set(MemorySegment seg, long index, int x) {
        constants$2.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


