// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     void* set_fields_data;
 *     jpegxl_cms_set_fields_from_icc_func set_fields_from_icc;
 *     void* init_data;
 *     jpegxl_cms_init_func init;
 *     jpegxl_cms_get_buffer_func get_src_buf;
 *     jpegxl_cms_get_buffer_func get_dst_buf;
 *     jpegxl_cms_run_func run;
 *     jpegxl_cms_destroy_func destroy;
 * };
 * }
 */
public class JxlCmsInterface {

    public static MemoryLayout $LAYOUT() {
        return constants$6.const$0;
    }
    public static VarHandle set_fields_data$VH() {
        return constants$6.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* set_fields_data;
     * }
     */
    public static MemorySegment set_fields_data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* set_fields_data;
     * }
     */
    public static void set_fields_data$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$1.set(seg, x);
    }
    public static MemorySegment set_fields_data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void set_fields_data$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle set_fields_from_icc$VH() {
        return constants$6.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc;
     * }
     */
    public static MemorySegment set_fields_from_icc$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc;
     * }
     */
    public static void set_fields_from_icc$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$2.set(seg, x);
    }
    public static MemorySegment set_fields_from_icc$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void set_fields_from_icc$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_set_fields_from_icc_func set_fields_from_icc(MemorySegment segment, Arena scope) {
        return jpegxl_cms_set_fields_from_icc_func.ofAddress(set_fields_from_icc$get(segment), scope);
    }
    public static VarHandle init_data$VH() {
        return constants$6.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* init_data;
     * }
     */
    public static MemorySegment init_data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* init_data;
     * }
     */
    public static void init_data$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$3.set(seg, x);
    }
    public static MemorySegment init_data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void init_data$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle init$VH() {
        return constants$6.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_init_func init;
     * }
     */
    public static MemorySegment init$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_init_func init;
     * }
     */
    public static void init$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$4.set(seg, x);
    }
    public static MemorySegment init$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void init$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_init_func init(MemorySegment segment, Arena scope) {
        return jpegxl_cms_init_func.ofAddress(init$get(segment), scope);
    }
    public static VarHandle get_src_buf$VH() {
        return constants$6.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_get_buffer_func get_src_buf;
     * }
     */
    public static MemorySegment get_src_buf$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_get_buffer_func get_src_buf;
     * }
     */
    public static void get_src_buf$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$5.set(seg, x);
    }
    public static MemorySegment get_src_buf$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void get_src_buf$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_get_buffer_func get_src_buf(MemorySegment segment, Arena scope) {
        return jpegxl_cms_get_buffer_func.ofAddress(get_src_buf$get(segment), scope);
    }
    public static VarHandle get_dst_buf$VH() {
        return constants$7.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_get_buffer_func get_dst_buf;
     * }
     */
    public static MemorySegment get_dst_buf$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$7.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_get_buffer_func get_dst_buf;
     * }
     */
    public static void get_dst_buf$set(MemorySegment seg, MemorySegment x) {
        constants$7.const$0.set(seg, x);
    }
    public static MemorySegment get_dst_buf$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$7.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void get_dst_buf$set(MemorySegment seg, long index, MemorySegment x) {
        constants$7.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_get_buffer_func get_dst_buf(MemorySegment segment, Arena scope) {
        return jpegxl_cms_get_buffer_func.ofAddress(get_dst_buf$get(segment), scope);
    }
    public static VarHandle run$VH() {
        return constants$7.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_run_func run;
     * }
     */
    public static MemorySegment run$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$7.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_run_func run;
     * }
     */
    public static void run$set(MemorySegment seg, MemorySegment x) {
        constants$7.const$1.set(seg, x);
    }
    public static MemorySegment run$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$7.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void run$set(MemorySegment seg, long index, MemorySegment x) {
        constants$7.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_run_func run(MemorySegment segment, Arena scope) {
        return jpegxl_cms_run_func.ofAddress(run$get(segment), scope);
    }
    public static VarHandle destroy$VH() {
        return constants$7.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_cms_destroy_func destroy;
     * }
     */
    public static MemorySegment destroy$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$7.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_cms_destroy_func destroy;
     * }
     */
    public static void destroy$set(MemorySegment seg, MemorySegment x) {
        constants$7.const$2.set(seg, x);
    }
    public static MemorySegment destroy$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$7.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void destroy$set(MemorySegment seg, long index, MemorySegment x) {
        constants$7.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_cms_destroy_func destroy(MemorySegment segment, Arena scope) {
        return jpegxl_cms_destroy_func.ofAddress(destroy$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


