// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct JxlChunkedFrameInputSource {
 *     void* opaque;
 *     void (*get_color_channels_pixel_format)(void*,JxlPixelFormat*);
 *     void* (*get_color_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t*);
 *     void (*get_extra_channel_pixel_format)(void*,size_t,JxlPixelFormat*);
 *     void* (*get_extra_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t,size_t*);
 *     void (*release_buffer)(void*,void*);
 * };
 * }
 */
public class JxlChunkedFrameInputSource {

    public static MemoryLayout $LAYOUT() {
        return constants$39.const$1;
    }
    public static VarHandle opaque$VH() {
        return constants$39.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static MemorySegment opaque$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$39.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static void opaque$set(MemorySegment seg, MemorySegment x) {
        constants$39.const$2.set(seg, x);
    }
    public static MemorySegment opaque$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$39.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void opaque$set(MemorySegment seg, long index, MemorySegment x) {
        constants$39.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * void (*get_color_channels_pixel_format)(void*,JxlPixelFormat*);
     * }
     */
    public interface get_color_channels_pixel_format {

        void apply(java.lang.foreign.MemorySegment opaque, java.lang.foreign.MemorySegment address);
        static MemorySegment allocate(get_color_channels_pixel_format fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$39.const$3, fi, constants$17.const$0, scope);
        }
        static get_color_channels_pixel_format ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment _opaque, java.lang.foreign.MemorySegment _address) -> {
                try {
                    constants$17.const$2.invokeExact(symbol, _opaque, _address);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_color_channels_pixel_format$VH() {
        return constants$39.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*get_color_channels_pixel_format)(void*,JxlPixelFormat*);
     * }
     */
    public static MemorySegment get_color_channels_pixel_format$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$39.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*get_color_channels_pixel_format)(void*,JxlPixelFormat*);
     * }
     */
    public static void get_color_channels_pixel_format$set(MemorySegment seg, MemorySegment x) {
        constants$39.const$4.set(seg, x);
    }
    public static MemorySegment get_color_channels_pixel_format$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$39.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void get_color_channels_pixel_format$set(MemorySegment seg, long index, MemorySegment x) {
        constants$39.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_color_channels_pixel_format get_color_channels_pixel_format(MemorySegment segment, Arena scope) {
        return get_color_channels_pixel_format.ofAddress(get_color_channels_pixel_format$get(segment), scope);
    }
    /**
     * {@snippet :
 * void* (*get_color_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public interface get_color_channel_data_at {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, java.lang.foreign.MemorySegment _x5);
        static MemorySegment allocate(get_color_channel_data_at fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$40.const$0, fi, constants$39.const$5, scope);
        }
        static get_color_channel_data_at ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1, long __x2, long __x3, long __x4, java.lang.foreign.MemorySegment __x5) -> {
                try {
                    return (java.lang.foreign.MemorySegment)constants$40.const$1.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4, __x5);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_color_channel_data_at$VH() {
        return constants$40.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* (*get_color_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public static MemorySegment get_color_channel_data_at$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$40.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* (*get_color_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public static void get_color_channel_data_at$set(MemorySegment seg, MemorySegment x) {
        constants$40.const$2.set(seg, x);
    }
    public static MemorySegment get_color_channel_data_at$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$40.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void get_color_channel_data_at$set(MemorySegment seg, long index, MemorySegment x) {
        constants$40.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_color_channel_data_at get_color_channel_data_at(MemorySegment segment, Arena scope) {
        return get_color_channel_data_at.ofAddress(get_color_channel_data_at$get(segment), scope);
    }
    /**
     * {@snippet :
 * void (*get_extra_channel_pixel_format)(void*,size_t,JxlPixelFormat*);
     * }
     */
    public interface get_extra_channel_pixel_format {

        void apply(java.lang.foreign.MemorySegment _x0, long _x1, java.lang.foreign.MemorySegment _x2);
        static MemorySegment allocate(get_extra_channel_pixel_format fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$40.const$4, fi, constants$40.const$3, scope);
        }
        static get_extra_channel_pixel_format ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1, java.lang.foreign.MemorySegment __x2) -> {
                try {
                    constants$40.const$5.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_extra_channel_pixel_format$VH() {
        return constants$41.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*get_extra_channel_pixel_format)(void*,size_t,JxlPixelFormat*);
     * }
     */
    public static MemorySegment get_extra_channel_pixel_format$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$41.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*get_extra_channel_pixel_format)(void*,size_t,JxlPixelFormat*);
     * }
     */
    public static void get_extra_channel_pixel_format$set(MemorySegment seg, MemorySegment x) {
        constants$41.const$0.set(seg, x);
    }
    public static MemorySegment get_extra_channel_pixel_format$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$41.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void get_extra_channel_pixel_format$set(MemorySegment seg, long index, MemorySegment x) {
        constants$41.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_extra_channel_pixel_format get_extra_channel_pixel_format(MemorySegment segment, Arena scope) {
        return get_extra_channel_pixel_format.ofAddress(get_extra_channel_pixel_format$get(segment), scope);
    }
    /**
     * {@snippet :
 * void* (*get_extra_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public interface get_extra_channel_data_at {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, long _x5, java.lang.foreign.MemorySegment _x6);
        static MemorySegment allocate(get_extra_channel_data_at fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$41.const$2, fi, constants$41.const$1, scope);
        }
        static get_extra_channel_data_at ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1, long __x2, long __x3, long __x4, long __x5, java.lang.foreign.MemorySegment __x6) -> {
                try {
                    return (java.lang.foreign.MemorySegment)constants$41.const$3.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4, __x5, __x6);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_extra_channel_data_at$VH() {
        return constants$41.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* (*get_extra_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public static MemorySegment get_extra_channel_data_at$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$41.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* (*get_extra_channel_data_at)(void*,size_t,size_t,size_t,size_t,size_t,size_t*);
     * }
     */
    public static void get_extra_channel_data_at$set(MemorySegment seg, MemorySegment x) {
        constants$41.const$4.set(seg, x);
    }
    public static MemorySegment get_extra_channel_data_at$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$41.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void get_extra_channel_data_at$set(MemorySegment seg, long index, MemorySegment x) {
        constants$41.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_extra_channel_data_at get_extra_channel_data_at(MemorySegment segment, Arena scope) {
        return get_extra_channel_data_at.ofAddress(get_extra_channel_data_at$get(segment), scope);
    }
    /**
     * {@snippet :
 * void (*release_buffer)(void*,void*);
     * }
     */
    public interface release_buffer {

        void apply(java.lang.foreign.MemorySegment opaque, java.lang.foreign.MemorySegment address);
        static MemorySegment allocate(release_buffer fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$41.const$5, fi, constants$17.const$0, scope);
        }
        static release_buffer ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment _opaque, java.lang.foreign.MemorySegment _address) -> {
                try {
                    constants$17.const$2.invokeExact(symbol, _opaque, _address);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle release_buffer$VH() {
        return constants$42.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*release_buffer)(void*,void*);
     * }
     */
    public static MemorySegment release_buffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$42.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*release_buffer)(void*,void*);
     * }
     */
    public static void release_buffer$set(MemorySegment seg, MemorySegment x) {
        constants$42.const$0.set(seg, x);
    }
    public static MemorySegment release_buffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$42.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void release_buffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$42.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static release_buffer release_buffer(MemorySegment segment, Arena scope) {
        return release_buffer.ofAddress(release_buffer$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


