// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     struct  icc;
 *     JxlColorEncoding color_encoding;
 *     size_t num_channels;
 * };
 * }
 */
public class JxlColorProfile {

    public static MemoryLayout $LAYOUT() {
        return constants$3.const$1;
    }
    /**
     * {@snippet :
     * struct {
     *     const uint8_t* data;
     *     size_t size;
     * };
     * }
     */
    public static final class icc {

        // Suppresses default constructor, ensuring non-instantiability.
        private icc() {}
        public static MemoryLayout $LAYOUT() {
            return constants$3.const$2;
        }
        public static VarHandle data$VH() {
            return constants$3.const$3;
        }
        /**
         * Getter for field:
         * {@snippet :
         * const uint8_t* data;
         * }
         */
        public static MemorySegment data$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$3.const$3.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * const uint8_t* data;
         * }
         */
        public static void data$set(MemorySegment seg, MemorySegment x) {
            constants$3.const$3.set(seg, x);
        }
        public static MemorySegment data$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$3.const$3.get(seg.asSlice(index*sizeof()));
        }
        public static void data$set(MemorySegment seg, long index, MemorySegment x) {
            constants$3.const$3.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle size$VH() {
            return constants$3.const$4;
        }
        /**
         * Getter for field:
         * {@snippet :
         * size_t size;
         * }
         */
        public static long size$get(MemorySegment seg) {
            return (long)constants$3.const$4.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * size_t size;
         * }
         */
        public static void size$set(MemorySegment seg, long x) {
            constants$3.const$4.set(seg, x);
        }
        public static long size$get(MemorySegment seg, long index) {
            return (long)constants$3.const$4.get(seg.asSlice(index*sizeof()));
        }
        public static void size$set(MemorySegment seg, long index, long x) {
            constants$3.const$4.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment icc$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static MemorySegment color_encoding$slice(MemorySegment seg) {
        return seg.asSlice(16, 104);
    }
    public static VarHandle num_channels$VH() {
        return constants$3.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t num_channels;
     * }
     */
    public static long num_channels$get(MemorySegment seg) {
        return (long)constants$3.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t num_channels;
     * }
     */
    public static void num_channels$set(MemorySegment seg, long x) {
        constants$3.const$5.set(seg, x);
    }
    public static long num_channels$get(MemorySegment seg, long index) {
        return (long)constants$3.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void num_channels$set(MemorySegment seg, long index, long x) {
        constants$3.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


