// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*JxlDebugImageCallback)(void* opaque,char* label,unsigned long long xsize,unsigned long long ysize,struct * color,unsigned short* pixels);
 * }
 */
public interface JxlDebugImageCallback {

    void apply(java.lang.foreign.MemorySegment opaque, java.lang.foreign.MemorySegment label, long xsize, long ysize, java.lang.foreign.MemorySegment color, java.lang.foreign.MemorySegment pixels);
    static MemorySegment allocate(JxlDebugImageCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$48.const$3, fi, constants$48.const$2, scope);
    }
    static JxlDebugImageCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _opaque, java.lang.foreign.MemorySegment _label, long _xsize, long _ysize, java.lang.foreign.MemorySegment _color, java.lang.foreign.MemorySegment _pixels) -> {
            try {
                constants$48.const$4.invokeExact(symbol, _opaque, _label, _xsize, _ysize, _color, _pixels);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


