// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct JxlEncoderOutputProcessor {
 *     void* opaque;
 *     void* (*get_buffer)(void*,size_t*);
 *     void (*release_buffer)(void*,size_t);
 *     void (*seek)(void*,uint64_t);
 *     void (*set_finalized_position)(void*,uint64_t);
 * };
 * }
 */
public class JxlEncoderOutputProcessor {

    public static MemoryLayout $LAYOUT() {
        return constants$36.const$3;
    }
    public static VarHandle opaque$VH() {
        return constants$36.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static MemorySegment opaque$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$36.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static void opaque$set(MemorySegment seg, MemorySegment x) {
        constants$36.const$4.set(seg, x);
    }
    public static MemorySegment opaque$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$36.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void opaque$set(MemorySegment seg, long index, MemorySegment x) {
        constants$36.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * void* (*get_buffer)(void*,size_t*);
     * }
     */
    public interface get_buffer {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1);
        static MemorySegment allocate(get_buffer fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$37.const$0, fi, constants$36.const$5, scope);
        }
        static get_buffer ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1) -> {
                try {
                    return (java.lang.foreign.MemorySegment)constants$37.const$1.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_buffer$VH() {
        return constants$37.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* (*get_buffer)(void*,size_t*);
     * }
     */
    public static MemorySegment get_buffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$37.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* (*get_buffer)(void*,size_t*);
     * }
     */
    public static void get_buffer$set(MemorySegment seg, MemorySegment x) {
        constants$37.const$2.set(seg, x);
    }
    public static MemorySegment get_buffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$37.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void get_buffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$37.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_buffer get_buffer(MemorySegment segment, Arena scope) {
        return get_buffer.ofAddress(get_buffer$get(segment), scope);
    }
    /**
     * {@snippet :
 * void (*release_buffer)(void*,size_t);
     * }
     */
    public interface release_buffer {

        void apply(java.lang.foreign.MemorySegment _x0, long _x1);
        static MemorySegment allocate(release_buffer fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$37.const$3, fi, constants$21.const$0, scope);
        }
        static release_buffer ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1) -> {
                try {
                    constants$37.const$4.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle release_buffer$VH() {
        return constants$37.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*release_buffer)(void*,size_t);
     * }
     */
    public static MemorySegment release_buffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$37.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*release_buffer)(void*,size_t);
     * }
     */
    public static void release_buffer$set(MemorySegment seg, MemorySegment x) {
        constants$37.const$5.set(seg, x);
    }
    public static MemorySegment release_buffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$37.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void release_buffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$37.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static release_buffer release_buffer(MemorySegment segment, Arena scope) {
        return release_buffer.ofAddress(release_buffer$get(segment), scope);
    }
    /**
     * {@snippet :
 * void (*seek)(void*,uint64_t);
     * }
     */
    public interface seek {

        void apply(java.lang.foreign.MemorySegment _x0, long _x1);
        static MemorySegment allocate(seek fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$38.const$0, fi, constants$21.const$0, scope);
        }
        static seek ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1) -> {
                try {
                    constants$37.const$4.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle seek$VH() {
        return constants$38.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*seek)(void*,uint64_t);
     * }
     */
    public static MemorySegment seek$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$38.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*seek)(void*,uint64_t);
     * }
     */
    public static void seek$set(MemorySegment seg, MemorySegment x) {
        constants$38.const$1.set(seg, x);
    }
    public static MemorySegment seek$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$38.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void seek$set(MemorySegment seg, long index, MemorySegment x) {
        constants$38.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static seek seek(MemorySegment segment, Arena scope) {
        return seek.ofAddress(seek$get(segment), scope);
    }
    /**
     * {@snippet :
 * void (*set_finalized_position)(void*,uint64_t);
     * }
     */
    public interface set_finalized_position {

        void apply(java.lang.foreign.MemorySegment _x0, long _x1);
        static MemorySegment allocate(set_finalized_position fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$38.const$2, fi, constants$21.const$0, scope);
        }
        static set_finalized_position ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1) -> {
                try {
                    constants$37.const$4.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle set_finalized_position$VH() {
        return constants$38.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*set_finalized_position)(void*,uint64_t);
     * }
     */
    public static MemorySegment set_finalized_position$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$38.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*set_finalized_position)(void*,uint64_t);
     * }
     */
    public static void set_finalized_position$set(MemorySegment seg, MemorySegment x) {
        constants$38.const$3.set(seg, x);
    }
    public static MemorySegment set_finalized_position$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$38.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void set_finalized_position$set(MemorySegment seg, long index, MemorySegment x) {
        constants$38.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static set_finalized_position set_finalized_position(MemorySegment segment, Arena scope) {
        return set_finalized_position.ofAddress(set_finalized_position$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


