// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     uint32_t duration;
 *     uint32_t timecode;
 *     uint32_t name_length;
 *     int is_last;
 *     JxlLayerInfo layer_info;
 * };
 * }
 */
public class JxlFrameHeader {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$0;
    }
    public static VarHandle duration$VH() {
        return constants$16.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t duration;
     * }
     */
    public static int duration$get(MemorySegment seg) {
        return (int)constants$16.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t duration;
     * }
     */
    public static void duration$set(MemorySegment seg, int x) {
        constants$16.const$1.set(seg, x);
    }
    public static int duration$get(MemorySegment seg, long index) {
        return (int)constants$16.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void duration$set(MemorySegment seg, long index, int x) {
        constants$16.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle timecode$VH() {
        return constants$16.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t timecode;
     * }
     */
    public static int timecode$get(MemorySegment seg) {
        return (int)constants$16.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t timecode;
     * }
     */
    public static void timecode$set(MemorySegment seg, int x) {
        constants$16.const$2.set(seg, x);
    }
    public static int timecode$get(MemorySegment seg, long index) {
        return (int)constants$16.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void timecode$set(MemorySegment seg, long index, int x) {
        constants$16.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle name_length$VH() {
        return constants$16.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t name_length;
     * }
     */
    public static int name_length$get(MemorySegment seg) {
        return (int)constants$16.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t name_length;
     * }
     */
    public static void name_length$set(MemorySegment seg, int x) {
        constants$16.const$3.set(seg, x);
    }
    public static int name_length$get(MemorySegment seg, long index) {
        return (int)constants$16.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void name_length$set(MemorySegment seg, long index, int x) {
        constants$16.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle is_last$VH() {
        return constants$16.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int is_last;
     * }
     */
    public static int is_last$get(MemorySegment seg) {
        return (int)constants$16.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int is_last;
     * }
     */
    public static void is_last$set(MemorySegment seg, int x) {
        constants$16.const$4.set(seg, x);
    }
    public static int is_last$get(MemorySegment seg, long index) {
        return (int)constants$16.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void is_last$set(MemorySegment seg, long index, int x) {
        constants$16.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment layer_info$slice(MemorySegment seg) {
        return seg.asSlice(16, 40);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


