// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*JxlImageOutCallback)(void* opaque,unsigned long long x,unsigned long long y,unsigned long long num_pixels,void* pixels);
 * }
 */
public interface JxlImageOutCallback {

    void apply(java.lang.foreign.MemorySegment opaque, long x, long y, long num_pixels, java.lang.foreign.MemorySegment pixels);
    static MemorySegment allocate(JxlImageOutCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$28.const$2, fi, constants$28.const$1, scope);
    }
    static JxlImageOutCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _opaque, long _x, long _y, long _num_pixels, java.lang.foreign.MemorySegment _pixels) -> {
            try {
                constants$28.const$3.invokeExact(symbol, _opaque, _x, _y, _num_pixels, _pixels);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


