// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*JxlImageOutRunCallback)(void* run_opaque,unsigned long long thread_id,unsigned long long x,unsigned long long y,unsigned long long num_pixels,void* pixels);
 * }
 */
public interface JxlImageOutRunCallback {

    void apply(java.lang.foreign.MemorySegment run_opaque, long thread_id, long x, long y, long num_pixels, java.lang.foreign.MemorySegment pixels);
    static MemorySegment allocate(JxlImageOutRunCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$29.const$2, fi, constants$29.const$1, scope);
    }
    static JxlImageOutRunCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _run_opaque, long _thread_id, long _x, long _y, long _num_pixels, java.lang.foreign.MemorySegment _pixels) -> {
            try {
                constants$29.const$3.invokeExact(symbol, _run_opaque, _thread_id, _x, _y, _num_pixels, _pixels);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


