// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void* (*JxlImageOutInitCallback)(void* init_opaque,unsigned long long num_threads,unsigned long long num_pixels_per_thread);
 * }
 */
public interface JxlImageOutInitCallback {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment init_opaque, long num_threads, long num_pixels_per_thread);
    static MemorySegment allocate(JxlImageOutInitCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$28.const$5, fi, constants$28.const$4, scope);
    }
    static JxlImageOutInitCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _init_opaque, long _num_threads, long _num_pixels_per_thread) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$29.const$0.invokeExact(symbol, _init_opaque, _num_threads, _num_pixels_per_thread);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


