// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int have_crop;
 *     int32_t crop_x0;
 *     int32_t crop_y0;
 *     uint32_t xsize;
 *     uint32_t ysize;
 *     JxlBlendInfo blend_info;
 *     uint32_t save_as_reference;
 * };
 * }
 */
public class JxlLayerInfo {

    public static MemoryLayout $LAYOUT() {
        return constants$14.const$5;
    }
    public static VarHandle have_crop$VH() {
        return constants$15.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int have_crop;
     * }
     */
    public static int have_crop$get(MemorySegment seg) {
        return (int)constants$15.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int have_crop;
     * }
     */
    public static void have_crop$set(MemorySegment seg, int x) {
        constants$15.const$0.set(seg, x);
    }
    public static int have_crop$get(MemorySegment seg, long index) {
        return (int)constants$15.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void have_crop$set(MemorySegment seg, long index, int x) {
        constants$15.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle crop_x0$VH() {
        return constants$15.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t crop_x0;
     * }
     */
    public static int crop_x0$get(MemorySegment seg) {
        return (int)constants$15.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t crop_x0;
     * }
     */
    public static void crop_x0$set(MemorySegment seg, int x) {
        constants$15.const$1.set(seg, x);
    }
    public static int crop_x0$get(MemorySegment seg, long index) {
        return (int)constants$15.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void crop_x0$set(MemorySegment seg, long index, int x) {
        constants$15.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle crop_y0$VH() {
        return constants$15.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t crop_y0;
     * }
     */
    public static int crop_y0$get(MemorySegment seg) {
        return (int)constants$15.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t crop_y0;
     * }
     */
    public static void crop_y0$set(MemorySegment seg, int x) {
        constants$15.const$2.set(seg, x);
    }
    public static int crop_y0$get(MemorySegment seg, long index) {
        return (int)constants$15.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void crop_y0$set(MemorySegment seg, long index, int x) {
        constants$15.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle xsize$VH() {
        return constants$15.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t xsize;
     * }
     */
    public static int xsize$get(MemorySegment seg) {
        return (int)constants$15.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t xsize;
     * }
     */
    public static void xsize$set(MemorySegment seg, int x) {
        constants$15.const$3.set(seg, x);
    }
    public static int xsize$get(MemorySegment seg, long index) {
        return (int)constants$15.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void xsize$set(MemorySegment seg, long index, int x) {
        constants$15.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ysize$VH() {
        return constants$15.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t ysize;
     * }
     */
    public static int ysize$get(MemorySegment seg) {
        return (int)constants$15.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t ysize;
     * }
     */
    public static void ysize$set(MemorySegment seg, int x) {
        constants$15.const$4.set(seg, x);
    }
    public static int ysize$get(MemorySegment seg, long index) {
        return (int)constants$15.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void ysize$set(MemorySegment seg, long index, int x) {
        constants$15.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment blend_info$slice(MemorySegment seg) {
        return seg.asSlice(20, 16);
    }
    public static VarHandle save_as_reference$VH() {
        return constants$15.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t save_as_reference;
     * }
     */
    public static int save_as_reference$get(MemorySegment seg) {
        return (int)constants$15.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t save_as_reference;
     * }
     */
    public static void save_as_reference$set(MemorySegment seg, int x) {
        constants$15.const$5.set(seg, x);
    }
    public static int save_as_reference$get(MemorySegment seg, long index) {
        return (int)constants$15.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void save_as_reference$set(MemorySegment seg, long index, int x) {
        constants$15.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


