// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct JxlMemoryManagerStruct {
 *     void* opaque;
 *     jpegxl_alloc_func alloc;
 *     jpegxl_free_func free;
 * };
 * }
 */
public class JxlMemoryManagerStruct {

    public static MemoryLayout $LAYOUT() {
        return constants$17.const$3;
    }
    public static VarHandle opaque$VH() {
        return constants$17.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static MemorySegment opaque$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* opaque;
     * }
     */
    public static void opaque$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$4.set(seg, x);
    }
    public static MemorySegment opaque$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void opaque$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle alloc$VH() {
        return constants$17.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_alloc_func alloc;
     * }
     */
    public static MemorySegment alloc$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_alloc_func alloc;
     * }
     */
    public static void alloc$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$5.set(seg, x);
    }
    public static MemorySegment alloc$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void alloc$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_alloc_func alloc(MemorySegment segment, Arena scope) {
        return jpegxl_alloc_func.ofAddress(alloc$get(segment), scope);
    }
    public static VarHandle free$VH() {
        return constants$18.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * jpegxl_free_func free;
     * }
     */
    public static MemorySegment free$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$18.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * jpegxl_free_func free;
     * }
     */
    public static void free$set(MemorySegment seg, MemorySegment x) {
        constants$18.const$0.set(seg, x);
    }
    public static MemorySegment free$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$18.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void free$set(MemorySegment seg, long index, MemorySegment x) {
        constants$18.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static jpegxl_free_func free(MemorySegment segment, Arena scope) {
        return jpegxl_free_func.ofAddress(free$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


