// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*JxlParallelRunFunction)(void* jpegxl_opaque,unsigned int value,unsigned long long thread_id);
 * }
 */
public interface JxlParallelRunFunction {

    void apply(java.lang.foreign.MemorySegment jpegxl_opaque, int value, long thread_id);
    static MemorySegment allocate(JxlParallelRunFunction fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$18.const$5, fi, constants$18.const$4, scope);
    }
    static JxlParallelRunFunction ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _jpegxl_opaque, int _value, long _thread_id) -> {
            try {
                constants$19.const$0.invokeExact(symbol, _jpegxl_opaque, _value, _thread_id);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


