// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*JxlParallelRunInit)(void* jpegxl_opaque,unsigned long long num_threads);
 * }
 */
public interface JxlParallelRunInit {

    int apply(java.lang.foreign.MemorySegment jpegxl_opaque, long num_threads);
    static MemorySegment allocate(JxlParallelRunInit fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$18.const$2, fi, constants$18.const$1, scope);
    }
    static JxlParallelRunInit ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _jpegxl_opaque, long _num_threads) -> {
            try {
                return (int)constants$18.const$3.invokeExact(symbol, _jpegxl_opaque, _num_threads);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


