// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     uint32_t xsize;
 *     uint32_t ysize;
 * };
 * }
 */
public class JxlPreviewHeader {

    public static MemoryLayout $LAYOUT() {
        return constants$7.const$3;
    }
    public static VarHandle xsize$VH() {
        return constants$7.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t xsize;
     * }
     */
    public static int xsize$get(MemorySegment seg) {
        return (int)constants$7.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t xsize;
     * }
     */
    public static void xsize$set(MemorySegment seg, int x) {
        constants$7.const$4.set(seg, x);
    }
    public static int xsize$get(MemorySegment seg, long index) {
        return (int)constants$7.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void xsize$set(MemorySegment seg, long index, int x) {
        constants$7.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ysize$VH() {
        return constants$7.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t ysize;
     * }
     */
    public static int ysize$get(MemorySegment seg) {
        return (int)constants$7.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t ysize;
     * }
     */
    public static void ysize$set(MemorySegment seg, int x) {
        constants$7.const$5.set(seg, x);
    }
    public static int ysize$get(MemorySegment seg, long index) {
        return (int)constants$7.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ysize$set(MemorySegment seg, long index, int x) {
        constants$7.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


