// Generated by jextract

package panamage.jxl.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef void *(*jpegxl_cms_init_func)(void *, size_t, size_t, const JxlColorProfile *, const JxlColorProfile *, float)
 * }
 */
public final class jpegxl_cms_init_func {

    private jpegxl_cms_init_func() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment init_data, long num_threads, long pixels_per_thread, MemorySegment input_profile, MemorySegment output_profile, float intensity_target);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_LONG_LONG,
        Jxl.C_LONG_LONG,
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_FLOAT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Jxl.upcallHandle(jpegxl_cms_init_func.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(jpegxl_cms_init_func.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment init_data, long num_threads, long pixels_per_thread, MemorySegment input_profile, MemorySegment output_profile, float intensity_target) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, init_data, num_threads, pixels_per_thread, input_profile, output_profile, intensity_target);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

