// Generated by jextract

package panamage.jxl.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef int (*jpegxl_cms_run_func)(void *, size_t, const float *, float *, size_t)
 * }
 */
public final class jpegxl_cms_run_func {

    private jpegxl_cms_run_func() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment user_data, long thread, MemorySegment input_buffer, MemorySegment output_buffer, long num_pixels);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Jxl.C_INT,
        Jxl.C_POINTER,
        Jxl.C_LONG_LONG,
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_LONG_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Jxl.upcallHandle(jpegxl_cms_run_func.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(jpegxl_cms_run_func.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment user_data, long thread, MemorySegment input_buffer, MemorySegment output_buffer, long num_pixels) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, user_data, thread, input_buffer, output_buffer, num_pixels);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

