// Generated by jextract

package panamage.jxl.ffi;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.ValueLayout.OfInt;
import java.util.function.Consumer;

/**
 * {@snippet lang=c :
 * struct {
 *     JxlBitDepthType type;
 *     uint32_t bits_per_sample;
 *     uint32_t exponent_bits_per_sample;
 * }
 * }
 */
public class JxlBitDepth {

    JxlBitDepth() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_INT.withName("type"),
        Jxl.C_INT.withName("bits_per_sample"),
        Jxl.C_INT.withName("exponent_bits_per_sample")
    ).withName("$anon$133:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * JxlBitDepthType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * JxlBitDepthType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * JxlBitDepthType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * JxlBitDepthType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt bits_per_sample$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bits_per_sample"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t bits_per_sample
     * }
     */
    public static final OfInt bits_per_sample$layout() {
        return bits_per_sample$LAYOUT;
    }

    private static final long bits_per_sample$OFFSET = $LAYOUT.byteOffset(groupElement("bits_per_sample"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t bits_per_sample
     * }
     */
    public static final long bits_per_sample$offset() {
        return bits_per_sample$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t bits_per_sample
     * }
     */
    public static int bits_per_sample(MemorySegment struct) {
        return struct.get(bits_per_sample$LAYOUT, bits_per_sample$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t bits_per_sample
     * }
     */
    public static void bits_per_sample(MemorySegment struct, int fieldValue) {
        struct.set(bits_per_sample$LAYOUT, bits_per_sample$OFFSET, fieldValue);
    }

    private static final OfInt exponent_bits_per_sample$LAYOUT = (OfInt)$LAYOUT.select(groupElement("exponent_bits_per_sample"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t exponent_bits_per_sample
     * }
     */
    public static final OfInt exponent_bits_per_sample$layout() {
        return exponent_bits_per_sample$LAYOUT;
    }

    private static final long exponent_bits_per_sample$OFFSET = $LAYOUT.byteOffset(groupElement("exponent_bits_per_sample"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t exponent_bits_per_sample
     * }
     */
    public static final long exponent_bits_per_sample$offset() {
        return exponent_bits_per_sample$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t exponent_bits_per_sample
     * }
     */
    public static int exponent_bits_per_sample(MemorySegment struct) {
        return struct.get(exponent_bits_per_sample$LAYOUT, exponent_bits_per_sample$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t exponent_bits_per_sample
     * }
     */
    public static void exponent_bits_per_sample(MemorySegment struct, int fieldValue) {
        struct.set(exponent_bits_per_sample$LAYOUT, exponent_bits_per_sample$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

