// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     JxlBlendMode blendmode;
 *     uint32_t source;
 *     uint32_t alpha;
 *     int clamp;
 * }
 * }
 */
public class JxlBlendInfo {

    JxlBlendInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_INT.withName("blendmode"),
        Jxl.C_INT.withName("source"),
        Jxl.C_INT.withName("alpha"),
        Jxl.C_INT.withName("clamp")
    ).withName("$anon$330:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt blendmode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("blendmode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * JxlBlendMode blendmode
     * }
     */
    public static final OfInt blendmode$layout() {
        return blendmode$LAYOUT;
    }

    private static final long blendmode$OFFSET = $LAYOUT.byteOffset(groupElement("blendmode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * JxlBlendMode blendmode
     * }
     */
    public static final long blendmode$offset() {
        return blendmode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * JxlBlendMode blendmode
     * }
     */
    public static int blendmode(MemorySegment struct) {
        return struct.get(blendmode$LAYOUT, blendmode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * JxlBlendMode blendmode
     * }
     */
    public static void blendmode(MemorySegment struct, int fieldValue) {
        struct.set(blendmode$LAYOUT, blendmode$OFFSET, fieldValue);
    }

    private static final OfInt source$LAYOUT = (OfInt)$LAYOUT.select(groupElement("source"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t source
     * }
     */
    public static final OfInt source$layout() {
        return source$LAYOUT;
    }

    private static final long source$OFFSET = $LAYOUT.byteOffset(groupElement("source"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t source
     * }
     */
    public static final long source$offset() {
        return source$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t source
     * }
     */
    public static int source(MemorySegment struct) {
        return struct.get(source$LAYOUT, source$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t source
     * }
     */
    public static void source(MemorySegment struct, int fieldValue) {
        struct.set(source$LAYOUT, source$OFFSET, fieldValue);
    }

    private static final OfInt alpha$LAYOUT = (OfInt)$LAYOUT.select(groupElement("alpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t alpha
     * }
     */
    public static final OfInt alpha$layout() {
        return alpha$LAYOUT;
    }

    private static final long alpha$OFFSET = $LAYOUT.byteOffset(groupElement("alpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t alpha
     * }
     */
    public static final long alpha$offset() {
        return alpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t alpha
     * }
     */
    public static int alpha(MemorySegment struct) {
        return struct.get(alpha$LAYOUT, alpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t alpha
     * }
     */
    public static void alpha(MemorySegment struct, int fieldValue) {
        struct.set(alpha$LAYOUT, alpha$OFFSET, fieldValue);
    }

    private static final OfInt clamp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int clamp
     * }
     */
    public static final OfInt clamp$layout() {
        return clamp$LAYOUT;
    }

    private static final long clamp$OFFSET = $LAYOUT.byteOffset(groupElement("clamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int clamp
     * }
     */
    public static final long clamp$offset() {
        return clamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int clamp
     * }
     */
    public static int clamp(MemorySegment struct) {
        return struct.get(clamp$LAYOUT, clamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int clamp
     * }
     */
    public static void clamp(MemorySegment struct, int fieldValue) {
        struct.set(clamp$LAYOUT, clamp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

