// Generated by jextract

package panamage.jxl.ffi;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

/**
 * {@snippet lang=c :
 * struct {
 *     void *set_fields_data;
 *     jpegxl_cms_set_fields_from_icc_func set_fields_from_icc;
 *     void *init_data;
 *     jpegxl_cms_init_func init;
 *     jpegxl_cms_get_buffer_func get_src_buf;
 *     jpegxl_cms_get_buffer_func get_dst_buf;
 *     jpegxl_cms_run_func run;
 *     jpegxl_cms_destroy_func destroy;
 * }
 * }
 */
public class JxlCmsInterface {

    JxlCmsInterface() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_POINTER.withName("set_fields_data"),
        Jxl.C_POINTER.withName("set_fields_from_icc"),
        Jxl.C_POINTER.withName("init_data"),
        Jxl.C_POINTER.withName("init"),
        Jxl.C_POINTER.withName("get_src_buf"),
        Jxl.C_POINTER.withName("get_dst_buf"),
        Jxl.C_POINTER.withName("run"),
        Jxl.C_POINTER.withName("destroy")
    ).withName("$anon$227:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout set_fields_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_fields_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *set_fields_data
     * }
     */
    public static final AddressLayout set_fields_data$layout() {
        return set_fields_data$LAYOUT;
    }

    private static final long set_fields_data$OFFSET = $LAYOUT.byteOffset(groupElement("set_fields_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *set_fields_data
     * }
     */
    public static final long set_fields_data$offset() {
        return set_fields_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *set_fields_data
     * }
     */
    public static MemorySegment set_fields_data(MemorySegment struct) {
        return struct.get(set_fields_data$LAYOUT, set_fields_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *set_fields_data
     * }
     */
    public static void set_fields_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_fields_data$LAYOUT, set_fields_data$OFFSET, fieldValue);
    }

    private static final AddressLayout set_fields_from_icc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_fields_from_icc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc
     * }
     */
    public static final AddressLayout set_fields_from_icc$layout() {
        return set_fields_from_icc$LAYOUT;
    }

    private static final long set_fields_from_icc$OFFSET = $LAYOUT.byteOffset(groupElement("set_fields_from_icc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc
     * }
     */
    public static final long set_fields_from_icc$offset() {
        return set_fields_from_icc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc
     * }
     */
    public static MemorySegment set_fields_from_icc(MemorySegment struct) {
        return struct.get(set_fields_from_icc$LAYOUT, set_fields_from_icc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_set_fields_from_icc_func set_fields_from_icc
     * }
     */
    public static void set_fields_from_icc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_fields_from_icc$LAYOUT, set_fields_from_icc$OFFSET, fieldValue);
    }

    private static final AddressLayout init_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *init_data
     * }
     */
    public static final AddressLayout init_data$layout() {
        return init_data$LAYOUT;
    }

    private static final long init_data$OFFSET = $LAYOUT.byteOffset(groupElement("init_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *init_data
     * }
     */
    public static final long init_data$offset() {
        return init_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *init_data
     * }
     */
    public static MemorySegment init_data(MemorySegment struct) {
        return struct.get(init_data$LAYOUT, init_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *init_data
     * }
     */
    public static void init_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init_data$LAYOUT, init_data$OFFSET, fieldValue);
    }

    private static final AddressLayout init$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_init_func init
     * }
     */
    public static final AddressLayout init$layout() {
        return init$LAYOUT;
    }

    private static final long init$OFFSET = $LAYOUT.byteOffset(groupElement("init"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_init_func init
     * }
     */
    public static final long init$offset() {
        return init$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_init_func init
     * }
     */
    public static MemorySegment init(MemorySegment struct) {
        return struct.get(init$LAYOUT, init$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_init_func init
     * }
     */
    public static void init(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init$LAYOUT, init$OFFSET, fieldValue);
    }

    private static final AddressLayout get_src_buf$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_src_buf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_src_buf
     * }
     */
    public static final AddressLayout get_src_buf$layout() {
        return get_src_buf$LAYOUT;
    }

    private static final long get_src_buf$OFFSET = $LAYOUT.byteOffset(groupElement("get_src_buf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_src_buf
     * }
     */
    public static final long get_src_buf$offset() {
        return get_src_buf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_src_buf
     * }
     */
    public static MemorySegment get_src_buf(MemorySegment struct) {
        return struct.get(get_src_buf$LAYOUT, get_src_buf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_src_buf
     * }
     */
    public static void get_src_buf(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_src_buf$LAYOUT, get_src_buf$OFFSET, fieldValue);
    }

    private static final AddressLayout get_dst_buf$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_dst_buf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_dst_buf
     * }
     */
    public static final AddressLayout get_dst_buf$layout() {
        return get_dst_buf$LAYOUT;
    }

    private static final long get_dst_buf$OFFSET = $LAYOUT.byteOffset(groupElement("get_dst_buf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_dst_buf
     * }
     */
    public static final long get_dst_buf$offset() {
        return get_dst_buf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_dst_buf
     * }
     */
    public static MemorySegment get_dst_buf(MemorySegment struct) {
        return struct.get(get_dst_buf$LAYOUT, get_dst_buf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_get_buffer_func get_dst_buf
     * }
     */
    public static void get_dst_buf(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_dst_buf$LAYOUT, get_dst_buf$OFFSET, fieldValue);
    }

    private static final AddressLayout run$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("run"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_run_func run
     * }
     */
    public static final AddressLayout run$layout() {
        return run$LAYOUT;
    }

    private static final long run$OFFSET = $LAYOUT.byteOffset(groupElement("run"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_run_func run
     * }
     */
    public static final long run$offset() {
        return run$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_run_func run
     * }
     */
    public static MemorySegment run(MemorySegment struct) {
        return struct.get(run$LAYOUT, run$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_run_func run
     * }
     */
    public static void run(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(run$LAYOUT, run$OFFSET, fieldValue);
    }

    private static final AddressLayout destroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("destroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * jpegxl_cms_destroy_func destroy
     * }
     */
    public static final AddressLayout destroy$layout() {
        return destroy$LAYOUT;
    }

    private static final long destroy$OFFSET = $LAYOUT.byteOffset(groupElement("destroy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * jpegxl_cms_destroy_func destroy
     * }
     */
    public static final long destroy$offset() {
        return destroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * jpegxl_cms_destroy_func destroy
     * }
     */
    public static MemorySegment destroy(MemorySegment struct) {
        return struct.get(destroy$LAYOUT, destroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * jpegxl_cms_destroy_func destroy
     * }
     */
    public static void destroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(destroy$LAYOUT, destroy$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

