// Generated by jextract

package panamage.jxl.ffi;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.invoke.MethodHandle;
import java.util.function.Consumer;

/**
 * {@snippet lang=c :
 * struct JxlChunkedFrameInputSource {
 *     void *opaque;
 *     void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *);
 *     const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *);
 *     void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *);
 *     const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *);
 *     void (*release_buffer)(void *, const void *);
 * }
 * }
 */
public class JxlChunkedFrameInputSource {

    JxlChunkedFrameInputSource() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_POINTER.withName("opaque"),
        Jxl.C_POINTER.withName("get_color_channels_pixel_format"),
        Jxl.C_POINTER.withName("get_color_channel_data_at"),
        Jxl.C_POINTER.withName("get_extra_channel_pixel_format"),
        Jxl.C_POINTER.withName("get_extra_channel_data_at"),
        Jxl.C_POINTER.withName("release_buffer")
    ).withName("JxlChunkedFrameInputSource");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout opaque$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("opaque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final AddressLayout opaque$layout() {
        return opaque$LAYOUT;
    }

    private static final long opaque$OFFSET = $LAYOUT.byteOffset(groupElement("opaque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final long opaque$offset() {
        return opaque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static MemorySegment opaque(MemorySegment struct) {
        return struct.get(opaque$LAYOUT, opaque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static void opaque(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(opaque$LAYOUT, opaque$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *)
     * }
     */
    public final static class get_color_channels_pixel_format {

        private get_color_channels_pixel_format() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(get_color_channels_pixel_format.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_color_channels_pixel_format.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_color_channels_pixel_format$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_color_channels_pixel_format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *)
     * }
     */
    public static final AddressLayout get_color_channels_pixel_format$layout() {
        return get_color_channels_pixel_format$LAYOUT;
    }

    private static final long get_color_channels_pixel_format$OFFSET = $LAYOUT.byteOffset(groupElement("get_color_channels_pixel_format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *)
     * }
     */
    public static final long get_color_channels_pixel_format$offset() {
        return get_color_channels_pixel_format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *)
     * }
     */
    public static MemorySegment get_color_channels_pixel_format(MemorySegment struct) {
        return struct.get(get_color_channels_pixel_format$LAYOUT, get_color_channels_pixel_format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_color_channels_pixel_format)(void *, JxlPixelFormat *)
     * }
     */
    public static void get_color_channels_pixel_format(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_color_channels_pixel_format$LAYOUT, get_color_channels_pixel_format$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public final static class get_color_channel_data_at {

        private get_color_channel_data_at() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, MemorySegment _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Jxl.C_POINTER,
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(get_color_channel_data_at.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_color_channel_data_at.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, MemorySegment _x5) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_color_channel_data_at$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_color_channel_data_at"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static final AddressLayout get_color_channel_data_at$layout() {
        return get_color_channel_data_at$LAYOUT;
    }

    private static final long get_color_channel_data_at$OFFSET = $LAYOUT.byteOffset(groupElement("get_color_channel_data_at"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static final long get_color_channel_data_at$offset() {
        return get_color_channel_data_at$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static MemorySegment get_color_channel_data_at(MemorySegment struct) {
        return struct.get(get_color_channel_data_at$LAYOUT, get_color_channel_data_at$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *(*get_color_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static void get_color_channel_data_at(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_color_channel_data_at$LAYOUT, get_color_channel_data_at$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *)
     * }
     */
    public final static class get_extra_channel_pixel_format {

        private get_extra_channel_pixel_format() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(get_extra_channel_pixel_format.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_extra_channel_pixel_format.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_extra_channel_pixel_format$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_extra_channel_pixel_format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *)
     * }
     */
    public static final AddressLayout get_extra_channel_pixel_format$layout() {
        return get_extra_channel_pixel_format$LAYOUT;
    }

    private static final long get_extra_channel_pixel_format$OFFSET = $LAYOUT.byteOffset(groupElement("get_extra_channel_pixel_format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *)
     * }
     */
    public static final long get_extra_channel_pixel_format$offset() {
        return get_extra_channel_pixel_format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *)
     * }
     */
    public static MemorySegment get_extra_channel_pixel_format(MemorySegment struct) {
        return struct.get(get_extra_channel_pixel_format$LAYOUT, get_extra_channel_pixel_format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_extra_channel_pixel_format)(void *, size_t, JxlPixelFormat *)
     * }
     */
    public static void get_extra_channel_pixel_format(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_extra_channel_pixel_format$LAYOUT, get_extra_channel_pixel_format$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public final static class get_extra_channel_data_at {

        private get_extra_channel_data_at() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, long _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Jxl.C_POINTER,
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_LONG_LONG,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(get_extra_channel_data_at.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_extra_channel_data_at.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1, long _x2, long _x3, long _x4, long _x5, MemorySegment _x6) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_extra_channel_data_at$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_extra_channel_data_at"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static final AddressLayout get_extra_channel_data_at$layout() {
        return get_extra_channel_data_at$LAYOUT;
    }

    private static final long get_extra_channel_data_at$OFFSET = $LAYOUT.byteOffset(groupElement("get_extra_channel_data_at"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static final long get_extra_channel_data_at$offset() {
        return get_extra_channel_data_at$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static MemorySegment get_extra_channel_data_at(MemorySegment struct) {
        return struct.get(get_extra_channel_data_at$LAYOUT, get_extra_channel_data_at$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *(*get_extra_channel_data_at)(void *, size_t, size_t, size_t, size_t, size_t, size_t *)
     * }
     */
    public static void get_extra_channel_data_at(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_extra_channel_data_at$LAYOUT, get_extra_channel_data_at$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*release_buffer)(void *, const void *)
     * }
     */
    public final static class release_buffer {

        private release_buffer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(release_buffer.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(release_buffer.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout release_buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("release_buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, const void *)
     * }
     */
    public static final AddressLayout release_buffer$layout() {
        return release_buffer$LAYOUT;
    }

    private static final long release_buffer$OFFSET = $LAYOUT.byteOffset(groupElement("release_buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, const void *)
     * }
     */
    public static final long release_buffer$offset() {
        return release_buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, const void *)
     * }
     */
    public static MemorySegment release_buffer(MemorySegment struct) {
        return struct.get(release_buffer$LAYOUT, release_buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, const void *)
     * }
     */
    public static void release_buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(release_buffer$LAYOUT, release_buffer$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

