// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     struct {
 *         const uint8_t *data;
 *         size_t size;
 *     } icc;
 *     JxlColorEncoding color_encoding;
 *     size_t num_channels;
 * }
 * }
 */
public class JxlColorProfile {

    JxlColorProfile() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JxlColorProfile.icc.layout().withName("icc"),
        JxlColorEncoding.layout().withName("color_encoding"),
        Jxl.C_LONG_LONG.withName("num_channels")
    ).withName("$anon$47:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * struct {
     *     const uint8_t *data;
     *     size_t size;
     * }
     * }
     */
    public static class icc {

        icc() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            Jxl.C_POINTER.withName("data"),
            Jxl.C_LONG_LONG.withName("size")
        ).withName("$anon$49:3");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const uint8_t *data
         * }
         */
        public static final AddressLayout data$layout() {
            return data$LAYOUT;
        }

        private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const uint8_t *data
         * }
         */
        public static final long data$offset() {
            return data$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const uint8_t *data
         * }
         */
        public static MemorySegment data(MemorySegment struct) {
            return struct.get(data$LAYOUT, data$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const uint8_t *data
         * }
         */
        public static void data(MemorySegment struct, MemorySegment fieldValue) {
            struct.set(data$LAYOUT, data$OFFSET, fieldValue);
        }

        private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * size_t size
         * }
         */
        public static final OfLong size$layout() {
            return size$LAYOUT;
        }

        private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * size_t size
         * }
         */
        public static final long size$offset() {
            return size$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * size_t size
         * }
         */
        public static long size(MemorySegment struct) {
            return struct.get(size$LAYOUT, size$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * size_t size
         * }
         */
        public static void size(MemorySegment struct, long fieldValue) {
            struct.set(size$LAYOUT, size$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout icc$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("icc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct {
     *     const uint8_t *data;
     *     size_t size;
     * } icc
     * }
     */
    public static final GroupLayout icc$layout() {
        return icc$LAYOUT;
    }

    private static final long icc$OFFSET = $LAYOUT.byteOffset(groupElement("icc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct {
     *     const uint8_t *data;
     *     size_t size;
     * } icc
     * }
     */
    public static final long icc$offset() {
        return icc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct {
     *     const uint8_t *data;
     *     size_t size;
     * } icc
     * }
     */
    public static MemorySegment icc(MemorySegment struct) {
        return struct.asSlice(icc$OFFSET, icc$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct {
     *     const uint8_t *data;
     *     size_t size;
     * } icc
     * }
     */
    public static void icc(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, icc$OFFSET, icc$LAYOUT.byteSize());
    }

    private static final GroupLayout color_encoding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("color_encoding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * JxlColorEncoding color_encoding
     * }
     */
    public static final GroupLayout color_encoding$layout() {
        return color_encoding$LAYOUT;
    }

    private static final long color_encoding$OFFSET = $LAYOUT.byteOffset(groupElement("color_encoding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * JxlColorEncoding color_encoding
     * }
     */
    public static final long color_encoding$offset() {
        return color_encoding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * JxlColorEncoding color_encoding
     * }
     */
    public static MemorySegment color_encoding(MemorySegment struct) {
        return struct.asSlice(color_encoding$OFFSET, color_encoding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * JxlColorEncoding color_encoding
     * }
     */
    public static void color_encoding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, color_encoding$OFFSET, color_encoding$LAYOUT.byteSize());
    }

    private static final OfLong num_channels$LAYOUT = (OfLong)$LAYOUT.select(groupElement("num_channels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t num_channels
     * }
     */
    public static final OfLong num_channels$layout() {
        return num_channels$LAYOUT;
    }

    private static final long num_channels$OFFSET = $LAYOUT.byteOffset(groupElement("num_channels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t num_channels
     * }
     */
    public static final long num_channels$offset() {
        return num_channels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t num_channels
     * }
     */
    public static long num_channels(MemorySegment struct) {
        return struct.get(num_channels$LAYOUT, num_channels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t num_channels
     * }
     */
    public static void num_channels(MemorySegment struct, long fieldValue) {
        struct.set(num_channels$LAYOUT, num_channels$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

