// Generated by jextract

package panamage.jxl.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef void (*JxlDebugImageCallback)(void *, const char *, size_t, size_t, const JxlColorEncoding *, const uint16_t *)
 * }
 */
public final class JxlDebugImageCallback {

    private JxlDebugImageCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment opaque, MemorySegment label, long xsize, long ysize, MemorySegment color, MemorySegment pixels);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_LONG_LONG,
        Jxl.C_LONG_LONG,
        Jxl.C_POINTER,
        Jxl.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Jxl.upcallHandle(JxlDebugImageCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(JxlDebugImageCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment opaque, MemorySegment label, long xsize, long ysize, MemorySegment color, MemorySegment pixels) {
        try {
             DOWN$MH.invokeExact(funcPtr, opaque, label, xsize, ysize, color, pixels);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

