// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct JxlEncoderOutputProcessor {
 *     void *opaque;
 *     void *(*get_buffer)(void *, size_t *);
 *     void (*release_buffer)(void *, size_t);
 *     void (*seek)(void *, uint64_t);
 *     void (*set_finalized_position)(void *, uint64_t);
 * }
 * }
 */
public class JxlEncoderOutputProcessor {

    JxlEncoderOutputProcessor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_POINTER.withName("opaque"),
        Jxl.C_POINTER.withName("get_buffer"),
        Jxl.C_POINTER.withName("release_buffer"),
        Jxl.C_POINTER.withName("seek"),
        Jxl.C_POINTER.withName("set_finalized_position")
    ).withName("JxlEncoderOutputProcessor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout opaque$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("opaque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final AddressLayout opaque$layout() {
        return opaque$LAYOUT;
    }

    private static final long opaque$OFFSET = $LAYOUT.byteOffset(groupElement("opaque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final long opaque$offset() {
        return opaque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static MemorySegment opaque(MemorySegment struct) {
        return struct.get(opaque$LAYOUT, opaque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static void opaque(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(opaque$LAYOUT, opaque$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void *(*get_buffer)(void *, size_t *)
     * }
     */
    public final static class get_buffer {

        private get_buffer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Jxl.C_POINTER,
            Jxl.C_POINTER,
            Jxl.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(get_buffer.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_buffer.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *(*get_buffer)(void *, size_t *)
     * }
     */
    public static final AddressLayout get_buffer$layout() {
        return get_buffer$LAYOUT;
    }

    private static final long get_buffer$OFFSET = $LAYOUT.byteOffset(groupElement("get_buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *(*get_buffer)(void *, size_t *)
     * }
     */
    public static final long get_buffer$offset() {
        return get_buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *(*get_buffer)(void *, size_t *)
     * }
     */
    public static MemorySegment get_buffer(MemorySegment struct) {
        return struct.get(get_buffer$LAYOUT, get_buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *(*get_buffer)(void *, size_t *)
     * }
     */
    public static void get_buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_buffer$LAYOUT, get_buffer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*release_buffer)(void *, size_t)
     * }
     */
    public final static class release_buffer {

        private release_buffer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(release_buffer.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(release_buffer.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout release_buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("release_buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, size_t)
     * }
     */
    public static final AddressLayout release_buffer$layout() {
        return release_buffer$LAYOUT;
    }

    private static final long release_buffer$OFFSET = $LAYOUT.byteOffset(groupElement("release_buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, size_t)
     * }
     */
    public static final long release_buffer$offset() {
        return release_buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, size_t)
     * }
     */
    public static MemorySegment release_buffer(MemorySegment struct) {
        return struct.get(release_buffer$LAYOUT, release_buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*release_buffer)(void *, size_t)
     * }
     */
    public static void release_buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(release_buffer$LAYOUT, release_buffer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*seek)(void *, uint64_t)
     * }
     */
    public final static class seek {

        private seek() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(seek.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(seek.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout seek$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("seek"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*seek)(void *, uint64_t)
     * }
     */
    public static final AddressLayout seek$layout() {
        return seek$LAYOUT;
    }

    private static final long seek$OFFSET = $LAYOUT.byteOffset(groupElement("seek"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*seek)(void *, uint64_t)
     * }
     */
    public static final long seek$offset() {
        return seek$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*seek)(void *, uint64_t)
     * }
     */
    public static MemorySegment seek(MemorySegment struct) {
        return struct.get(seek$LAYOUT, seek$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*seek)(void *, uint64_t)
     * }
     */
    public static void seek(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(seek$LAYOUT, seek$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_finalized_position)(void *, uint64_t)
     * }
     */
    public final static class set_finalized_position {

        private set_finalized_position() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Jxl.C_POINTER,
            Jxl.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Jxl.upcallHandle(set_finalized_position.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_finalized_position.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, long _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_finalized_position$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_finalized_position"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_finalized_position)(void *, uint64_t)
     * }
     */
    public static final AddressLayout set_finalized_position$layout() {
        return set_finalized_position$LAYOUT;
    }

    private static final long set_finalized_position$OFFSET = $LAYOUT.byteOffset(groupElement("set_finalized_position"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_finalized_position)(void *, uint64_t)
     * }
     */
    public static final long set_finalized_position$offset() {
        return set_finalized_position$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_finalized_position)(void *, uint64_t)
     * }
     */
    public static MemorySegment set_finalized_position(MemorySegment struct) {
        return struct.get(set_finalized_position$LAYOUT, set_finalized_position$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_finalized_position)(void *, uint64_t)
     * }
     */
    public static void set_finalized_position(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_finalized_position$LAYOUT, set_finalized_position$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

