// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int have_crop;
 *     int32_t crop_x0;
 *     int32_t crop_y0;
 *     uint32_t xsize;
 *     uint32_t ysize;
 *     JxlBlendInfo blend_info;
 *     uint32_t save_as_reference;
 * }
 * }
 */
public class JxlLayerInfo {

    JxlLayerInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Jxl.C_INT.withName("have_crop"),
        Jxl.C_INT.withName("crop_x0"),
        Jxl.C_INT.withName("crop_y0"),
        Jxl.C_INT.withName("xsize"),
        Jxl.C_INT.withName("ysize"),
        JxlBlendInfo.layout().withName("blend_info"),
        Jxl.C_INT.withName("save_as_reference")
    ).withName("$anon$351:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt have_crop$LAYOUT = (OfInt)$LAYOUT.select(groupElement("have_crop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int have_crop
     * }
     */
    public static final OfInt have_crop$layout() {
        return have_crop$LAYOUT;
    }

    private static final long have_crop$OFFSET = $LAYOUT.byteOffset(groupElement("have_crop"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int have_crop
     * }
     */
    public static final long have_crop$offset() {
        return have_crop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int have_crop
     * }
     */
    public static int have_crop(MemorySegment struct) {
        return struct.get(have_crop$LAYOUT, have_crop$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int have_crop
     * }
     */
    public static void have_crop(MemorySegment struct, int fieldValue) {
        struct.set(have_crop$LAYOUT, have_crop$OFFSET, fieldValue);
    }

    private static final OfInt crop_x0$LAYOUT = (OfInt)$LAYOUT.select(groupElement("crop_x0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t crop_x0
     * }
     */
    public static final OfInt crop_x0$layout() {
        return crop_x0$LAYOUT;
    }

    private static final long crop_x0$OFFSET = $LAYOUT.byteOffset(groupElement("crop_x0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t crop_x0
     * }
     */
    public static final long crop_x0$offset() {
        return crop_x0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t crop_x0
     * }
     */
    public static int crop_x0(MemorySegment struct) {
        return struct.get(crop_x0$LAYOUT, crop_x0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t crop_x0
     * }
     */
    public static void crop_x0(MemorySegment struct, int fieldValue) {
        struct.set(crop_x0$LAYOUT, crop_x0$OFFSET, fieldValue);
    }

    private static final OfInt crop_y0$LAYOUT = (OfInt)$LAYOUT.select(groupElement("crop_y0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t crop_y0
     * }
     */
    public static final OfInt crop_y0$layout() {
        return crop_y0$LAYOUT;
    }

    private static final long crop_y0$OFFSET = $LAYOUT.byteOffset(groupElement("crop_y0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t crop_y0
     * }
     */
    public static final long crop_y0$offset() {
        return crop_y0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t crop_y0
     * }
     */
    public static int crop_y0(MemorySegment struct) {
        return struct.get(crop_y0$LAYOUT, crop_y0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t crop_y0
     * }
     */
    public static void crop_y0(MemorySegment struct, int fieldValue) {
        struct.set(crop_y0$LAYOUT, crop_y0$OFFSET, fieldValue);
    }

    private static final OfInt xsize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("xsize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static final OfInt xsize$layout() {
        return xsize$LAYOUT;
    }

    private static final long xsize$OFFSET = $LAYOUT.byteOffset(groupElement("xsize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static final long xsize$offset() {
        return xsize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static int xsize(MemorySegment struct) {
        return struct.get(xsize$LAYOUT, xsize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static void xsize(MemorySegment struct, int fieldValue) {
        struct.set(xsize$LAYOUT, xsize$OFFSET, fieldValue);
    }

    private static final OfInt ysize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ysize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static final OfInt ysize$layout() {
        return ysize$LAYOUT;
    }

    private static final long ysize$OFFSET = $LAYOUT.byteOffset(groupElement("ysize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static final long ysize$offset() {
        return ysize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static int ysize(MemorySegment struct) {
        return struct.get(ysize$LAYOUT, ysize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static void ysize(MemorySegment struct, int fieldValue) {
        struct.set(ysize$LAYOUT, ysize$OFFSET, fieldValue);
    }

    private static final GroupLayout blend_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("blend_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * JxlBlendInfo blend_info
     * }
     */
    public static final GroupLayout blend_info$layout() {
        return blend_info$LAYOUT;
    }

    private static final long blend_info$OFFSET = $LAYOUT.byteOffset(groupElement("blend_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * JxlBlendInfo blend_info
     * }
     */
    public static final long blend_info$offset() {
        return blend_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * JxlBlendInfo blend_info
     * }
     */
    public static MemorySegment blend_info(MemorySegment struct) {
        return struct.asSlice(blend_info$OFFSET, blend_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * JxlBlendInfo blend_info
     * }
     */
    public static void blend_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, blend_info$OFFSET, blend_info$LAYOUT.byteSize());
    }

    private static final OfInt save_as_reference$LAYOUT = (OfInt)$LAYOUT.select(groupElement("save_as_reference"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t save_as_reference
     * }
     */
    public static final OfInt save_as_reference$layout() {
        return save_as_reference$LAYOUT;
    }

    private static final long save_as_reference$OFFSET = $LAYOUT.byteOffset(groupElement("save_as_reference"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t save_as_reference
     * }
     */
    public static final long save_as_reference$offset() {
        return save_as_reference$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t save_as_reference
     * }
     */
    public static int save_as_reference(MemorySegment struct) {
        return struct.get(save_as_reference$LAYOUT, save_as_reference$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t save_as_reference
     * }
     */
    public static void save_as_reference(MemorySegment struct, int fieldValue) {
        struct.set(save_as_reference$LAYOUT, save_as_reference$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

