// Generated by jextract

package panamage.jxl.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct JxlMemoryManagerStruct {
 *     void *opaque;
 *     jpegxl_alloc_func alloc;
 *     jpegxl_free_func free;
 * } JxlMemoryManager
 * }
 */
public class JxlMemoryManager extends JxlMemoryManagerStruct {

    JxlMemoryManager() {
        // Should not be called directly
    }
}

