// Generated by jextract

package panamage.jxl.ffi;

/**
 * {@snippet lang=c :
 * typedef struct JxlMemoryManagerStruct {
 *     void *opaque;
 *     jpegxl_alloc_func alloc;
 *     jpegxl_free_func free;
 * } JxlMemoryManager
 * }
 */
public class JxlMemoryManager extends JxlMemoryManagerStruct {

    JxlMemoryManager() {
        // Should not be called directly
    }
}

