// Generated by jextract

package panamage.jxl.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef JxlParallelRetCode (*JxlParallelRunner)(void *, void *, JxlParallelRunInit, JxlParallelRunFunction, uint32_t, uint32_t)
 * }
 */
public final class JxlParallelRunner {

    private JxlParallelRunner() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment runner_opaque, MemorySegment jpegxl_opaque, MemorySegment init, MemorySegment func, int start_range, int end_range);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Jxl.C_INT,
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_POINTER,
        Jxl.C_INT,
        Jxl.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Jxl.upcallHandle(JxlParallelRunner.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(JxlParallelRunner.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment runner_opaque, MemorySegment jpegxl_opaque, MemorySegment init, MemorySegment func, int start_range, int end_range) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, runner_opaque, jpegxl_opaque, init, func, start_range, end_range);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

